# create a docker image from source code
#{port in my pc (host)} : {port in container}
version: '3.9'
services:
  back-end-nestjs:
    container_name: back-end-nestjs
    build:
      context: .
      dockerfile: Dockerfile
      # args:
      #   - NODE_ENV=development
    # restart: unless-stopped
    environment:
    # DB_HOST=postgres là host của db
      - DB_HOST=db-postgres
      - DB_PORT=db-postgres
      - DB_USERNAME=postgres
      - DB_PASSWORD=123123
      - DB_DATABASE=fresher
      - BE_PORT=5000

    # env_file:
    #   - .env
    ports:
      - '5000:5000'
    depends_on:
      - db-postgres
    # volumes:
    #   - app-data:/usr/src/app/dist/src

  db-postgres:
    container_name: db-postgres
    image: postgres:15.2-alpine
    restart: always
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=123123
      - POSTGRES_DB=fresher
    ports:
      - '5444:5432'
    volumes: 
      - db:/var/lib/postgresql/data

volumes:
  db:
#   app-data: